name: Prettier format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      
      - name: Install dependencies
        run: "npm i"

      - name: Check prettier
        run: "npm run format:check"

      - name: Check lint
        run: "npm run lint:check"
